apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-training
spec:
  template:
    spec:
      volumes:
        - name: test-store
          hostPath:
            path: "/var/tmp"
      containers:
        - name: tweets-training
          image: srishti95/neuralnet_sentiment:1.0.0
          volumeMounts:
            - mountPath: "/tmp"
              name: test-store
          ports:
          - containerPort: 8001
      restartPolicy: Never
  backoffLimit: 3
